FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

# Mise à jour de pip3
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Copie du fichier de lancement
COPY startup.sh startup.sh

# Copie du fichier config streamlit
RUN mkdir -p /.streamlit
COPY /.streamlit/.secrets /.streamlit/.secrets

# Copie des fichiers applicatifs
RUN mkdir -p /app
COPY /app/main.py /app/main.py
COPY /app/fonctions.py /app/fonctions.py

# On ouvre et expose le port 8501
EXPOSE 5000

#CMD ["/bin/bash","-c","startup.sh"]
ENTRYPOINT ["streamlit", "run", "/app/main.py", "--server.port=5000", "--server.address=0.0.0.0"]